import { HomeBodyContainer } from './styles';

export default function HomeBody() {
	return (
		<HomeBodyContainer>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
			<h1>Home Body</h1>
		</HomeBodyContainer>
	);
}
